(function(){var n=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,c,g){if(a==Array.prototype||a==Object.prototype)return a;a[c]=g.value;return a},v=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var c=0;c<a.length;++c){var g=a[c];if(g&&g.Math==Math)return g}throw Error("Cannot find global object");},w=v(this),x=function(a,c){if(c)a:{var g=w;a=a.split(".");for(var f=0;f<a.length-
1;f++){var e=a[f];if(!(e in g))break a;g=g[e]}a=a[a.length-1];f=g[a];c=c(f);c!=f&&c!=null&&n(g,a,{configurable:!0,writable:!0,value:c})}},y=function(a){var c=0;return function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}}},z=function(a){var c=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(c)return c.call(a);if(typeof a.length=="number")return{next:y(a)};throw Error(String(a)+" is not an iterable or ArrayLike");};x("globalThis",function(a){return a||w});
x("Promise",function(a){function c(){this.g=null}function g(b){return b instanceof e?b:new e(function(d){d(b)})}if(a)return a;c.prototype.v=function(b){if(this.g==null){this.g=[];var d=this;this.A(function(){d.L()})}this.g.push(b)};var f=w.setTimeout;c.prototype.A=function(b){f(b,0)};c.prototype.L=function(){for(;this.g&&this.g.length;){var b=this.g;this.g=[];for(var d=0;d<b.length;++d){var h=b[d];b[d]=null;try{h()}catch(k){this.K(k)}}}this.g=null};c.prototype.K=function(b){this.A(function(){throw b;
})};var e=function(b){this.i=0;this.j=void 0;this.h=[];this.G=!1;var d=this.o();try{b(d.resolve,d.reject)}catch(h){d.reject(h)}};e.prototype.o=function(){function b(k){return function(l){h||(h=!0,k.call(d,l))}}var d=this,h=!1;return{resolve:b(this.R),reject:b(this.u)}};e.prototype.R=function(b){if(b===this)this.u(new TypeError("A Promise cannot resolve to itself"));else if(b instanceof e)this.T(b);else{a:switch(typeof b){case "object":var d=b!=null;break a;case "function":d=!0;break a;default:d=!1}d?
this.P(b):this.F(b)}};e.prototype.P=function(b){var d=void 0;try{d=b.then}catch(h){this.u(h);return}typeof d=="function"?this.U(d,b):this.F(b)};e.prototype.u=function(b){this.J(2,b)};e.prototype.F=function(b){this.J(1,b)};e.prototype.J=function(b,d){if(this.i!=0)throw Error("Cannot settle("+b+", "+d+"): Promise already settled in state"+this.i);this.i=b;this.j=d;this.i===2&&this.S();this.M()};e.prototype.S=function(){var b=this;f(function(){if(b.N()){var d=w.console;typeof d!=="undefined"&&d.error(b.j)}},
1)};e.prototype.N=function(){if(this.G)return!1;var b=w.CustomEvent,d=w.Event,h=w.dispatchEvent;if(typeof h==="undefined")return!0;typeof b==="function"?b=new b("unhandledrejection",{cancelable:!0}):typeof d==="function"?b=new d("unhandledrejection",{cancelable:!0}):(b=w.document.createEvent("CustomEvent"),b.initCustomEvent("unhandledrejection",!1,!0,b));b.promise=this;b.reason=this.j;return h(b)};e.prototype.M=function(){if(this.h!=null){for(var b=0;b<this.h.length;++b)q.v(this.h[b]);this.h=null}};
var q=new c;e.prototype.T=function(b){var d=this.o();b.l(d.resolve,d.reject)};e.prototype.U=function(b,d){var h=this.o();try{b.call(d,h.resolve,h.reject)}catch(k){h.reject(k)}};e.prototype.then=function(b,d){function h(m,p){return typeof m=="function"?function(r){try{k(m(r))}catch(t){l(t)}}:p}var k,l,u=new e(function(m,p){k=m;l=p});this.l(h(b,k),h(d,l));return u};e.prototype.catch=function(b){return this.then(void 0,b)};e.prototype.l=function(b,d){function h(){switch(k.i){case 1:b(k.j);break;case 2:d(k.j);
break;default:throw Error("Unexpected state: "+k.i);}}var k=this;this.h==null?q.v(h):this.h.push(h);this.G=!0};e.resolve=g;e.reject=function(b){return new e(function(d,h){h(b)})};e.race=function(b){return new e(function(d,h){for(var k=z(b),l=k.next();!l.done;l=k.next())g(l.value).l(d,h)})};e.all=function(b){var d=z(b),h=d.next();return h.done?g([]):new e(function(k,l){function u(r){return function(t){m[r]=t;p--;p==0&&k(m)}}var m=[],p=0;do m.push(void 0),p++,g(h.value).l(u(m.length-1),l),h=d.next();
while(!h.done)})};return e});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var A=this||self,B=function(a,c){a=a.split(".");for(var g=A,f;a.length&&(f=a.shift());)a.length||c===void 0?g=g[f]&&g[f]!==Object.prototype[f]?g[f]:g[f]={}:g[f]=c};/*

 Copyright Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
var C={};function D(){if(C!==C)throw Error("Bad secret");};var E=globalThis.trustedTypes,F;function G(){var a=null;if(!E)return a;try{var c=function(g){return g};a=E.createPolicy("goog#html",{createHTML:c,createScript:c,createScriptURL:c})}catch(g){throw g;}return a};var H=function(a){D();this.I=a};H.prototype.toString=function(){return this.I+""};var I=function(a){D();this.O=a};I.prototype.toString=function(){return this.O};new I("about:blank");new I("about:invalid#zClosurez");var J=[],K=function(a){console.warn("A URL with content '"+a+"' was sanitized away.")};J.indexOf(K)===-1&&J.push(K);function L(a,c){if(c instanceof H)c=c.I;else throw Error("Unexpected type when unwrapping TrustedResourceUrl");a.src=c;var g;c=a.ownerDocument;c=c===void 0?document:c;var f;c=(f=(g=c).querySelector)==null?void 0:f.call(g,"script[nonce]");(g=c==null?"":c.nonce||c.getAttribute("nonce")||"")&&a.setAttribute("nonce",g)};var M=function(a){var c;this.W=c=c===void 0?window:c;this.V=a;this.B=[];this.C=[];this.H=this.D=!1},N=function(a){a.m.onload=function(){};a.m.onerror=function(){};a.m.onreadystatechange=function(){}},O=function(a){var c=a.W.document,g=c.head||c.documentElement,f=c.createElement("script");a.m=f;f.async=!0;f.defer=!0;L(f,a.V);f.onload=f.onreadystatechange=function(){f.readyState&&f.readyState!="loaded"&&f.readyState!="complete"||(a.H=!0,N(a),a.B.forEach(function(e){return e()}))};f.onerror=function(){a.D=
!0;N(a);a.C.forEach(function(e){return e()})};g.appendChild(f)};M.prototype.load=function(a,c){this.H?a():this.B.push(a);this.D?c():this.C.push(c);this.m||O(this)};function P(a){var c;F===void 0&&(F=G());a=(c=F)?c.createScriptURL(a):a;return new H(a)};function Q(a,c){var g=new M(a);B(c,function(f,e){f=f===void 0?function(){}:f;e=e===void 0?function(){}:e;return new Promise(function(q,b){g.load(function(){q();f()},function(){b();e()})})})}Q(P("https://www.gstatic.com/devops/connect/releases/devops-learning-tool-library_20260413_00_RC00/cloudshell/cloudshell.js"),"google.devops.tools.loadCloudShell");Q(P("https://www.gstatic.com/devops/connect/releases/devops-learning-tool-library_20260413_00_RC00/walkthrough/walkthrough.js"),"google.devops.tools.loadWalkthrough");}).call(this);
